# Generated by Django 4.2.7 on 2023-12-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='images/', verbose_name='商品主图', width_field='width'),
        ),
    ]
