# Generated by Django 4.2.7 on 2023-12-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_commodity_height_remove_commodity_width'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssistantImages',
        ),
        migrations.DeleteModel(
            name='Commodity',
        ),
    ]
