# Generated by Django 4.2.7 on 2023-12-25 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('details', models.TextField(max_length=2000, verbose_name='商品详情')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inventory', models.PositiveIntegerField(blank=True, default=0, verbose_name='商品库存')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='商品主图')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='商品主图')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.commodity')),
            ],
        ),
    ]
